### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [chapkachapka/george-bernard-shaw_mrs-warrens-profession#1]
# Semantics

- [x] In one case, you marked `<abbr>St.</abbr> James Gazette` as a play instead of a newspaper.
- [x] W. C. in `12 Buckingham Street, W. C.` seems like it should receive abbreviation semantics of some kind.
- [x] `Mrs.` should receive semantics in the colophon.

# Typography

- [x] You missed spelling out `22 percent`.

# Meta

- [x] 9e23972cc0507374bb5b61d51dbbf65d6da763c6, 47b7683b32ce617b52a4adcc8c7383ac6df034f7: I think it would be better to mark these as [Editorial].
- [x] 7a48772f15b7710032a59cd3057363ced738daee, 07c39e297184c6edbf7bc78dcfa4b3c25ddab656: Should be marked as editorial.

**Comment by chapkachapka** [comment]
Okay; this is how I screwed up my repo last time, so I wanted to check in advance what I need to do to rename the commits. My plan was to:

1. Use git amend and rename each relevant commit in vi
2. Force push the changes

Is that right?

**Comment by weijia-cheng** [comment]
Yes, so more specifically you should do `git rebase -i 9e23972~`, `reword` all of the offending commits, and force push the changes to the remote repository.

**Comment by chapkachapka** [comment]
Okay; that should all be done.
